### ISSUE TITLE
Update conflict with Microsoft.CodeAnalysis.Common 3.11.0

### ISSUE THREAD

**Issue by Djoums** [NetFabric/NetFabric.Hyperlinq.Analyzer#60]
When trying to update the Microsoft.CodeAnalysis.Common to version 3.11.0, I get the following error :

Error NU1107 Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.11.0 directly to project MyProject to resolve this issue.
MyProject -> Microsoft.CodeAnalysis.CSharp 3.11.0 -> Microsoft.CodeAnalysis.Common (= 3.11.0) 
MyProject -> NetFabric.Hyperlinq.Analyzer 2.0.4 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.10.0 -> Microsoft.CodeAnalysis.Common (= 3.10.0).

**Comment by aalmada** [comment]
I think this is fixed now
