### ISSUE TITLE
Migrate target framework to `net6.0` for `NetFabric.Hyperlinq.Analyzer.UnitTests`

### ISSUE THREAD

**Issue by xtqqczze** [NetFabric/NetFabric.Hyperlinq.Analyzer#67]
Migrate the target framework from `netcoreapp3.1` to `net6.0` – a supported LTS version.

https://devblogs.microsoft.com/dotnet/net-core-3-1-will-reach-end-of-support-on-december-13-2022/

**Comment by aalmada** [comment]
I'm working on it. Thanks!

**Comment by xtqqczze** [comment]
Fixed by #66.
